// Download NVM to help you install Node.JS
// https://codeforgeek.com/run-multiple-node-js-apps-with-different-node-js-version-in-same-server/
// you can use that link to help you
// run npm init --y
// then npm install --save express
// install the following import packages

const { application } = require("express")

// npm install express --save

// npm install body-parser --save

// npm install cookie-parser --save

// npm install ejs@3.1.6


// npm install multer --save

// to start run node app.js